festomo/config/routes.rb
Rails.application.routes.draw do
  
  root to: 'static_pages#home'
  get    'signup',  to: 'users#new'
  get    'login' ,  to: 'sessions#new'
  post   'login' ,  to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
end

festomo/app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  
end

festomo/app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    
    has_secure_password
    has_many :microposts
    
    def feed_items
        # Micropost.where(user_id: self.id)
        
    end
    
end

festomo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
  
  
end

festomo/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
   before_action :logged_in_user, only: [:create]
   
   def create
      @micropost = current_user.microposts.build(micropost_params) 
      if @micropost.save
         flash[:success] = "Micropost created!"
         redirect_to root_url
      else
         @feed_items=current_user.feed_items.includes(:user).order(createed_at: :desc)
         render 'static_pages/home'
      end
   
   end
   
   def destroy
      @micropost = current_user.microposts.find_by(id: params[:id])
      return redirect_to root_url if @micropost.nil?
      @micropost.destroy
      flash[:success] = "Micropost deleted"
      redirect_to request.referrer || root_url
   end   
   
   private
   def micropost_params
      params.require(:micropost).permit(:content)
   end   
   
end

festomo/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user= User.find_by(email:params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end  
    
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
  
end

festomo/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      # @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
      @feed_items = Micropost.all.includes(:user).order(created_at: :desc)
    end
  end
end

festomo/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def show
    @microposts = @user.microposts
  end
  
  def new
    @user=User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "ユーザー情報が更新されました"
      redirect_to @user
    else
      render :edit
    end
    
  end  

  private
  
  def set_user
      @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
  
  def user_edit_params
    params.require(:user).permit(:name, :email)
  end
end

festomo/app/helpers/application_helper.rb
module ApplicationHelper
end

festomo/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

festomo/app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

festomo/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Microposts", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  root_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dopdown">
            <a href="" class="dopdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>  
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end  %>
      </ul>
    </nav>
  </div>
</header>

festomo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microposts</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

festomo/app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
    <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
        <% if current_user == micropost.user %>
            <%= link_to "delete", micropost, method: :delete,
                                            data: { confirm: "You sure?" } %>
        <% end %>
    </span>
</li>

festomo/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

festomo/app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts">
        <%= render @feed_items %>
    </ol>
<% end %>

festomo/app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', object: f.object  %>
    <div class="field">
        <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>
    <%= f.submit "Post", class:"btn btn-primary" %>
<% end %>

festomo/app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size:50),current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

festomo/app/views/static_pages/home.html.erb
<% if logged_in? %>
   <div class="row">
      <aside class="col-md-4">
         <section class="user_info">
            <%= render 'shared/user_info' %>
         </section>
         <section class="micropost_form" >
            <%= render 'shared/micropost_form' %>
         </section>
      </aside>
      <div class="col-md-8">
         <h3>Timeline Feed</h3>
         <%= render 'shared/feed' %>
      </div>
   </div>
<% else %>
   <div class="center Jumbotron">
      <h1>Welcome to the FesTomo</h1>
      
      <%= link_to "Sing up now!", signup_path, class:"btn btn-lg btn-primary" %>
   </div>
<% end %>   

festomo/app/views/users/edit.html.erb
<h1>Edit my account</h1>

<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>


      <%= f.submit "Edit my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

festomo/app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

festomo/app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>Micropost (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
    <% end %>
  </div>
</div>